interface preDefinedTimeTableDataInterface {
    degreeId: string,
    branchId: string,
    semester: number,
    courseId: string,
    isLecture: number,
    isLab: number,
}


const CSE1: preDefinedTimeTableDataInterface[]= [
    {
        degreeId: "B.Tech",
        branchId: "CSE",
        semester: 1,
        courseId: "CSBB101",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CSE",
        semester: 1,
        courseId: "CSBB102",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CSE",
        semester: 1,
        courseId: "MALB101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "CSE",
        semester: 1,
        courseId: "HMBB101",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CSE",
        semester: 1,
        courseId: "MEBB162",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CSE",
        semester: 1,
        courseId: "HMPB102",
        isLecture: 0,
        isLab: 1,
    },
]


const AIDS1: preDefinedTimeTableDataInterface[]= [
    {
        degreeId: "B.Tech",
        branchId: "AIDS",
        semester: 1,
        courseId: "ADLB101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "AIDS",
        semester: 1,
        courseId: "ADLB102",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "AIDS",
        semester: 1,
        courseId: "ADBB103",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "AIDS",
        semester: 1,
        courseId: "ADBB104",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "AIDS",
        semester: 1,
        courseId: "PHBB112",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "AIDS",
        semester: 1,
        courseId: "HMLB102",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "AIDS",
        semester: 1,
        courseId: "EVPB102",
        isLecture: 0,
        isLab: 1,
    },
]


const ECE1: preDefinedTimeTableDataInterface[] = [
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "MALB101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "PHBB101",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "ECBB101",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "MEPB121",
        isLecture: 0,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "HMBB101",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "CELB101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "CEPB121",
        isLecture: 0,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ECE",
        semester: 1,
        courseId: "HMPB102",
        isLecture: 0,
        isLab: 1,
    },
]


const EE1: preDefinedTimeTableDataInterface[] = [
    {
        degreeId: "B.Tech",
        branchId: "EE",
        semester: 1,
        courseId: "PHL102",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "EE",
        semester: 1,
        courseId: "EEB102",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "EE",
        semester: 1,
        courseId: "MEB162",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "EE",
        semester: 1,
        courseId: "MAL101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "EE",
        semester: 1,
        courseId: "MEP121",
        isLecture: 0,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "EE",
        semester: 1,
        courseId: "HML101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "EE",
        semester: 1,
        courseId: "EVL101",
        isLecture: 1,
        isLab: 0,
    },
]


const ME1: preDefinedTimeTableDataInterface[] = [
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "MALB101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "PHBB111",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "MEBB111",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "HMLB101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "CSBB111",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "MELB101",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "MEPB122",
        isLecture: 0,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "ME",
        semester: 1,
        courseId: "CEPB101",
        isLecture: 0,
        isLab: 1,
    },
]


const CE1: preDefinedTimeTableDataInterface[] = [
    {
        degreeId: "B.Tech",
        branchId: "CE",
        semester: 1,
        courseId: "CELB102",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "CE",
        semester: 1,
        courseId: "CELB103",
        isLecture: 1,
        isLab: 0,
    },
    {
        degreeId: "B.Tech",
        branchId: "CE",
        semester: 1,
        courseId: "CELB104",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CE",
        semester: 1,
        courseId: "HMPB102",
        isLecture: 0,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CE",
        semester: 1,
        courseId: "ECBB101",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CE",
        semester: 1,
        courseId: "MEBB119",
        isLecture: 1,
        isLab: 1,
    },
    {
        degreeId: "B.Tech",
        branchId: "CE",
        semester: 1,
        courseId: "MALB159",
        isLecture: 1,
        isLab: 0,
    },
]


export const preDefinedTTData1: preDefinedTimeTableDataInterface[] = [
    ...AIDS1,
    ...CSE1,
    ...ECE1,
    ...EE1,
    ...ME1,
    ...CE1
]